# Generated by Django 3.0.5 on 2021-03-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_auto_20210328_1917'),
        ('artworks', '0003_auto_20210328_1632'),
    ]

    operations = [
    ]
